import type { Metadata } from "next";
// import { Inter } from "next/font/google"; fuente predeterminada
import "./globals.css";
import NavBar from "@/components/NavBar";
import { montserrat } from "./ui/fonts";
import Provider from "./Provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}> {/* de esta manera se importa la fuente */}
          <Provider>
            <NavBar />
            {children}
          </Provider>
      </body>
    </html>
  );
}
